from enum import Enum

class UserRole(Enum):
    ADMIN = "ADMIN"
    STUDENT = "STUDENT"
    TEACHER = "TEACHER"
    PARENT = "PARENT"
    CONTENTCREATOR = "CONTENTCREATOR"
    CONTENTVALIDATOR = "CONTENTVALIDATOR"
