# Generated by Django 5.0.6 on 2025-10-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='user',
            new_name='profile',
        ),
    ]
