# Generated by Django 5.0.6 on 2025-11-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_dob_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='moderation_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='county',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('REVIEW_REQUESTED', 'REVIEW_REQUESTED')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='district',
            name='moderation_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='district',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('REVIEW_REQUESTED', 'REVIEW_REQUESTED')], default='PENDING', max_length=30),
        ),
        migrations.AddField(
            model_name='school',
            name='moderation_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='school',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('REVIEW_REQUESTED', 'REVIEW_REQUESTED')], default='PENDING', max_length=30),
        ),
    ]
