# Generated by Django 5.0.6 on 2025-11-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_student_moderation_comment_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='moderation_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='teacher',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('REVIEW_REQUESTED', 'REVIEW_REQUESTED')], default='PENDING', max_length=30),
        ),
    ]
