# Generated by Django 5.0.6 on 2025-12-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_teacher_moderation_comment_teacher_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='parent_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
