# Generated by Django 5.0.6 on 2025-12-14 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_parent_parent_id_student_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counties_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
