# Generated by Django 5.0.6 on 2026-03-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_student_login_streak_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['grade', 'status'], name='accounts_st_grade_45a9e3_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'grade'], name='accounts_st_school__058555_idx'),
        ),
    ]
