# Generated by Django 5.0.6 on 2025-10-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_lessonresource_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/subjects/'),
        ),
    ]
