# Generated by Django 5.0.6 on 2025-10-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_subject_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalassessment',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonassessment',
            name='due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonresource',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated duration in minutes', null=True),
        ),
    ]
