# Generated by Django 5.0.6 on 2025-10-27 11:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_dob_user_gender'),
        ('content', '0004_generalassessment_due_at_lessonassessment_due_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='generalassessment',
            name='grade',
            field=models.CharField(blank=True, choices=[('GRADE 1', 'GRADE 1'), ('GRADE 2', 'GRADE 2'), ('GRADE 3', 'GRADE 3'), ('GRADE 4', 'GRADE 4'), ('GRADE 5', 'GRADE 5'), ('GRADE 6', 'GRADE 6'), ('GRADE 7', 'GRADE 7'), ('GRADE 8', 'GRADE 8'), ('GRADE 9', 'GRADE 9'), ('GRADE 10', 'GRADE 10'), ('GRADE 11', 'GRADE 11'), ('GRADE 12', 'GRADE 12'), ('OTHER', 'OTHER')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='generalassessment',
            index=models.Index(fields=['due_at'], name='content_gen_due_at_cdbcc2_idx'),
        ),
        migrations.AddIndex(
            model_name='generalassessment',
            index=models.Index(fields=['grade', 'due_at'], name='content_gen_grade_9c4c7c_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonassessment',
            index=models.Index(fields=['due_at'], name='content_les_due_at_e592f7_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonassessment',
            index=models.Index(fields=['lesson', 'due_at'], name='content_les_lesson__205ca6_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonresource',
            index=models.Index(fields=['subject', 'created_at'], name='content_les_subject_3dfb5b_idx'),
        ),
        migrations.AddIndex(
            model_name='takelesson',
            index=models.Index(fields=['student', 'created_at'], name='content_tak_student_f82848_idx'),
        ),
        migrations.AddIndex(
            model_name='takelesson',
            index=models.Index(fields=['lesson', 'student'], name='content_tak_lesson__8760e9_idx'),
        ),
    ]
