# Generated by Django 5.0.6 on 2025-11-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_subject_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='objectives',
            field=models.TextField(blank=True, default=''),
        ),
    ]
