# Generated by Django 5.0.6 on 2025-11-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_subject_objectives'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonresource',
            name='instructor_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
