# Generated by Django 5.0.6 on 2025-11-17 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_lessonresource_instructor_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('instructions', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('hint', models.CharField(blank=True, default='', max_length=250)),
                ('correct_answer', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='word_games/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
