# Generated by Django 5.0.6 on 2025-11-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_gamemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='type',
            field=models.CharField(choices=[('MUSIC', 'MUSIC'), ('WORD_PUZZLE', 'WORD_PUZZLE'), ('SHAPE', 'SHAPE'), ('COLOR', 'COLOR'), ('NUMBER', 'NUMBER')], max_length=50),
        ),
    ]
