# Generated by Django 5.0.6 on 2025-11-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_gamemodel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='subject',
            name='objectives',
        ),
        migrations.AddField(
            model_name='subject',
            name='objectives',
            field=models.ManyToManyField(blank=True, related_name='subjects', to='content.objective'),
        ),
    ]
