# Generated by Django 5.0.6 on 2025-11-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_gamemodel_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalassessment',
            name='type',
            field=models.CharField(choices=[('QUIZ', 'QUIZ'), ('ASSIGNMENT', 'ASSIGNMENT'), ('TRIAL', 'TRIAL')], default='ASSIGNMENT', max_length=30),
        ),
        migrations.AddField(
            model_name='lessonassessment',
            name='type',
            field=models.CharField(choices=[('QUIZ', 'QUIZ'), ('ASSIGNMENT', 'ASSIGNMENT'), ('TRIAL', 'TRIAL')], default='QUIZ', max_length=30),
        ),
        migrations.AlterField(
            model_name='gamemodel',
            name='type',
            field=models.CharField(choices=[('MUSIC', 'MUSIC'), ('WORD_PUZZLE', 'WORD_PUZZLE'), ('IMAGE_PUZZLE', 'IMAGE_PUZZLE'), ('SHAPE', 'SHAPE'), ('COLOR', 'COLOR'), ('NUMBER', 'NUMBER')], max_length=50),
        ),
    ]
