# Generated by Django 5.0.6 on 2025-11-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_generalassessment_type_lessonassessment_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonresource',
            name='resource_url',
        ),
        migrations.AddField(
            model_name='lessonresource',
            name='resource',
            field=models.FileField(default=None, upload_to='lesson_resources/'),
            preserve_default=False,
        ),
    ]
