# Generated by Django 5.0.6 on 2025-11-20 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_dob_user_gender'),
        ('content', '0015_remove_lessonresource_resource_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('solution', models.TextField(blank=True, default='')),
                ('attachment', models.FileField(upload_to='assessment_solutions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='content.generalassessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_solutions', to='accounts.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='generalassessmentgrade',
            name='solution',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade', to='content.assessmentsolution'),
        ),
    ]
