# Generated by Django 5.0.6 on 2025-11-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_assessmentsolution_generalassessmentgrade_solution'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonresource',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/lessons/'),
        ),
    ]
