# Generated by Django 5.0.6 on 2025-11-22 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_dob_user_gender'),
        ('content', '0017_lessonresource_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_played_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='content.gamemodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='played_games', to='accounts.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'game'], name='content_gam_student_9b6c40_idx')],
                'unique_together': {('student', 'game')},
            },
        ),
    ]
