# Generated by Django 5.0.6 on 2025-11-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_gameplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamemodel',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('REVIEW_REQUESTED', 'REVIEW_REQUESTED')], default='DRAFT', max_length=30),
        ),
        migrations.AddField(
            model_name='generalassessment',
            name='moderation_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='generalassessment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('REVIEW_REQUESTED', 'REVIEW_REQUESTED')], default='DRAFT', max_length=30),
        ),
        migrations.AddField(
            model_name='lessonassessment',
            name='moderation_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lessonassessment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('REVIEW_REQUESTED', 'REVIEW_REQUESTED')], default='DRAFT', max_length=30),
        ),
        migrations.AddField(
            model_name='lessonresource',
            name='moderation_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='subject',
            name='moderation_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
