# Generated by Django 5.0.6 on 2025-11-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_gamemodel_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('REVIEW_REQUESTED', 'REVIEW_REQUESTED')], default='PENDING', max_length=30),
        ),
    ]
