# Generated by Django 5.0.6 on 2025-11-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_subject_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('REVIEW_REQUESTED', 'REVIEW_REQUESTED')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='generalassessment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('REVIEW_REQUESTED', 'REVIEW_REQUESTED')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='lessonassessment',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('REVIEW_REQUESTED', 'REVIEW_REQUESTED')], default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='lessonresource',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'DRAFT'), ('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED'), ('REVIEW_REQUESTED', 'REVIEW_REQUESTED')], default='PENDING', max_length=30),
        ),
    ]
