# Generated by Django 5.0.6 on 2025-11-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_alter_gamemodel_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='objectives',
        ),
        migrations.DeleteModel(
            name='Objective',
        ),
        migrations.AddField(
            model_name='subject',
            name='objectives',
            field=models.TextField(blank=True, default=''),
        ),
    ]
