# Generated by Django 5.0.6 on 2025-12-16 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_county_created_by'),
        ('content', '0022_remove_subject_objectives_delete_objective_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonAssessmentSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('solution', models.TextField(blank=True, default='')),
                ('attachment', models.FileField(upload_to='lesson_assessment_solutions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('lesson_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='content.lessonassessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_assessment_solutions', to='accounts.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
