# Generated by Django 5.0.6 on 2026-01-12 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_assessment_ai_targeting'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='generalassessment',
            new_name='content_gen_is_targ_992420_idx',
            old_name='content_gen_target_idx',
        ),
        migrations.RenameIndex(
            model_name='lessonassessment',
            new_name='content_les_is_targ_6a7a24_idx',
            old_name='content_les_target_idx',
        ),
    ]
