# Generated by Django 5.0.6 on 2026-03-14 00:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_student_login_streak_fields'),
        ('content', '0025_rename_content_gen_target_idx_content_gen_is_targ_992420_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assessmentsolution',
            index=models.Index(fields=['student', 'assessment'], name='content_ass_student_0ac7f9_idx'),
        ),
        migrations.AddIndex(
            model_name='generalassessment',
            index=models.Index(fields=['status', 'grade', 'due_at'], name='content_gen_status_9497c9_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonassessment',
            index=models.Index(fields=['lesson', 'status', 'is_targeted', 'target_student'], name='content_les_lesson__6fec07_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonassessmentsolution',
            index=models.Index(fields=['student', 'lesson_assessment'], name='content_les_student_52a9d6_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonresource',
            index=models.Index(fields=['subject', 'status', 'period', 'topic', 'id'], name='content_les_subject_a73cfc_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonresource',
            index=models.Index(fields=['status', 'created_at'], name='content_les_status_1c6342_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['grade', 'status', 'name'], name='content_sub_grade_dca749_idx'),
        ),
    ]
