# Generated by Django 5.0.6 on 2026-03-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_student_accounts_st_grade_45a9e3_idx_and_more'),
        ('content', '0026_assessmentsolution_content_ass_student_0ac7f9_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='generalassessmentgrade',
            index=models.Index(fields=['student', 'assessment'], name='content_gen_student_bef73d_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonassessmentgrade',
            index=models.Index(fields=['student', 'lesson_assessment'], name='content_les_student_5ddd36_idx'),
        ),
    ]
