# Generated by Django 5.0.6 on 2026-03-14 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_student_accounts_st_grade_45a9e3_idx_and_more'),
        ('content', '0027_generalassessmentgrade_content_gen_student_bef73d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTemporaryUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_unlocks', to='content.lessonresource')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_lesson_unlocks', to='accounts.student')),
                ('unlocked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_lesson_unlocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'lesson', 'expires_at', 'revoked_at'], name='content_les_student_22940c_idx'), models.Index(fields=['lesson', 'expires_at'], name='content_les_lesson__6c5dd5_idx')],
            },
        ),
    ]
