# Generated by Django 5.0.6 on 2026-03-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0028_lessontemporaryunlock"),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("GRADE 1", "GRADE 1"),
                            ("GRADE 2", "GRADE 2"),
                            ("GRADE 3", "GRADE 3"),
                            ("GRADE 4", "GRADE 4"),
                            ("GRADE 5", "GRADE 5"),
                            ("GRADE 6", "GRADE 6"),
                            ("GRADE 7", "GRADE 7"),
                            ("GRADE 8", "GRADE 8"),
                            ("GRADE 9", "GRADE 9"),
                            ("GRADE 10", "GRADE 10"),
                            ("GRADE 11", "GRADE 11"),
                            ("GRADE 12", "GRADE 12"),
                            ("OTHER", "OTHER"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tag", models.CharField(db_index=True, max_length=80)),
                ("estimated_minutes", models.PositiveSmallIntegerField(default=5)),
                ("body", models.TextField()),
                ("characters", models.JSONField(blank=True, default=list)),
                ("vocabulary", models.JSONField(blank=True, default=list)),
                ("moral", models.CharField(blank=True, default="", max_length=255)),
                ("cover_image", models.JSONField(blank=True, default=dict)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["grade", "tag", "is_published", "created_at"], name="content_stor_grade_t_9c0c2f_idx"),
                ],
            },
        ),
    ]
