# Generated by Django 5.0.6 on 2026-03-27 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0029_story'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='story',
            new_name='content_sto_grade_9a8281_idx',
            old_name='content_stor_grade_t_9c0c2f_idx',
        ),
    ]
