# Generated by Django 5.0.6 on 2026-03-27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_county_created_by'),
        ('content', '0030_rename_content_stor_grade_t_9c0c2f_idx_content_sto_grade_9a8281_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='generated_stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='story',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET_NULL, related_name='stories', to='accounts.school'),
        ),
        migrations.AlterField(
            model_name='story',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='story',
            name='tag',
            field=models.CharField(
                choices=[
                    ('Friendship', 'Friendship'),
                    ('Honesty', 'Honesty'),
                    ('Kindness', 'Kindness'),
                    ('Respect', 'Respect'),
                    ('Responsibility', 'Responsibility'),
                    ('Courage', 'Courage'),
                    ('Perseverance', 'Perseverance'),
                    ('Teamwork', 'Teamwork'),
                    ('Empathy', 'Empathy'),
                    ('Patience', 'Patience'),
                    ('Gratitude', 'Gratitude'),
                    ('Creativity', 'Creativity'),
                    ('Curiosity', 'Curiosity'),
                    ('Problem Solving', 'Problem Solving'),
                ],
                db_index=True,
                max_length=80,
            ),
        ),
        migrations.RemoveIndex(
            model_name='story',
            name='content_sto_grade_9a8281_idx',
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['is_published', 'school', 'grade', 'tag', 'created_at'], name='content_st_is_pub_5f4ea_idx'),
        ),
    ]
