# Generated by Django 5.0.6 on 2026-03-27 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_story_workflow_and_school_scope'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='story',
            new_name='content_sto_is_publ_1651eb_idx',
            old_name='content_st_is_pub_5f4ea_idx',
        ),
    ]
