# Generated by Django 5.0.6 on 2025-10-26 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('content', '0001_initial'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAbuseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('mark_review', models.CharField(blank=True, default='', max_length=120)),
                ('sample_msg', models.TextField(blank=True, default='')),
                ('forum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abuse_reports', to='forum.forum')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=500)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='content.lessonresource')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to='accounts.student')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
